name: API CI

on:
  schedule:
    - cron: "30 15 * * *"   # runs at 15:30 UTC and 9 PM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running STAGING build"
